#!/bin/bash

# Get the absolute path of the script, even if it's a symbolic link
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"

# Get the directory of the script
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
LARADOCK_ROOT="$SCRIPT_DIR/.."

cd "$LARADOCK_ROOT"

docker compose down 
