#!/bin/bash

# This script serves as a helper to run other scripts in this directory by passing them as arguments.
# If the specified script filename is not found, it will be redirected to the 'docker compose xxx' command.

# Get the absolute path of the script, even if it's a symbolic link
SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"

# Get the directory of the script
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
# echo "The script directory is: $SCRIPT_DIR"

LARADOCK_ROOT="$SCRIPT_DIR/.."

# Get the script_name and shift it from the arguments
script_name="$1"
shift

# Find the corresponding script in the current directory
script_path="$SCRIPT_DIR/$script_name"
# echo "The script directory is: $script_path"

# Check if the script exists and is executable
if [ -x "$script_path" ]; then
    # Execute the script with the remaining arguments
    "$script_path" "$@"
else
    echo "The script '$script_name' was not found or is not executable. Would you like to execute the following command?"
    read -p "docker compose $script_name $@ (y/n): " response
    if [ "$response" != "y" ]; then
        echo "Exiting the script."
        exit 1
    fi
    echo -ne '\n'
    docker compose --file="$LARADOCK_ROOT/docker-compose.yml" --project-directory="$LARADOCK_ROOT" "$script_name" "$@"
    exit 1
fi
